#define VERSION_MAJOR 1
#define VERSION_MINOR 10
#define VERSION_PATCH 1
#define VERSION_BUILD 0

#define _VERSION_STRING(a, b, c, d) #a "." #b "." #c "." #d
#define VERSION_STRING _VERSION_STRING(VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH, VERSION_BUILD)
