/*** Autogenerated by WIDL 8.5 from licdll.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __licdll_h__
#define __licdll_h__

#ifndef __WIDL_INLINE
#if defined(__cplusplus) || defined(_MSC_VER)
#define __WIDL_INLINE inline
#elif defined(__GNUC__)
#define __WIDL_INLINE __inline__
#endif
#endif

/* Forward declarations */

#ifndef __COMLicenseAgent_FWD_DEFINED__
#define __COMLicenseAgent_FWD_DEFINED__
#ifdef __cplusplus
typedef class COMLicenseAgent COMLicenseAgent;
#else
typedef struct COMLicenseAgent COMLicenseAgent;
#endif /* defined __cplusplus */
#endif /* defined __COMLicenseAgent_FWD_DEFINED__ */

#ifndef __ICOMLicenseAgent_FWD_DEFINED__
#define __ICOMLicenseAgent_FWD_DEFINED__
typedef interface ICOMLicenseAgent ICOMLicenseAgent;
#ifdef __cplusplus
interface ICOMLicenseAgent;
#endif /* __cplusplus */
#endif

#ifndef __ICOMLicenseAgent2_FWD_DEFINED__
#define __ICOMLicenseAgent2_FWD_DEFINED__
typedef interface ICOMLicenseAgent2 ICOMLicenseAgent2;
#ifdef __cplusplus
interface ICOMLicenseAgent2;
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <oaidl.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef __LICDLLLib_LIBRARY_DEFINED__
#define __LICDLLLib_LIBRARY_DEFINED__

DEFINE_GUID(LIBID_LICDLLLib, 0xc7879482, 0xf798, 0x4a74, 0xaf,0x43, 0xe8,0x87,0xfb,0xdc,0xed,0x40);

#ifndef __ICOMLicenseAgent_FWD_DEFINED__
#define __ICOMLicenseAgent_FWD_DEFINED__
typedef interface ICOMLicenseAgent ICOMLicenseAgent;
#ifdef __cplusplus
interface ICOMLicenseAgent;
#endif /* __cplusplus */
#endif

#ifndef __ICOMLicenseAgent2_FWD_DEFINED__
#define __ICOMLicenseAgent2_FWD_DEFINED__
typedef interface ICOMLicenseAgent2 ICOMLicenseAgent2;
#ifdef __cplusplus
interface ICOMLicenseAgent2;
#endif /* __cplusplus */
#endif

/*****************************************************************************
 * COMLicenseAgent coclass
 */

DEFINE_GUID(CLSID_COMLicenseAgent, 0xacadf079, 0xcbcd, 0x4032, 0x83,0xf2, 0xfa,0x47,0xc4,0xdb,0x09,0x6f);

#ifdef __cplusplus
class DECLSPEC_UUID("acadf079-cbcd-4032-83f2-fa47c4db096f") COMLicenseAgent;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(COMLicenseAgent, 0xacadf079, 0xcbcd, 0x4032, 0x83,0xf2, 0xfa,0x47,0xc4,0xdb,0x09,0x6f)
#endif
#endif

/*****************************************************************************
 * ICOMLicenseAgent interface
 */
#ifndef __ICOMLicenseAgent_INTERFACE_DEFINED__
#define __ICOMLicenseAgent_INTERFACE_DEFINED__

DEFINE_GUID(IID_ICOMLicenseAgent, 0xb8cbad79, 0x3f1f, 0x481a, 0xbb,0x0c, 0xe7,0xbb,0xd7,0x7b,0xdd,0xd1);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("b8cbad79-3f1f-481a-bb0c-e7bbd77bddd1")
ICOMLicenseAgent : public IDispatch
{
    virtual HRESULT STDMETHODCALLTYPE Initialize(
        ULONG dwBPC,
        ULONG dwMode,
        BSTR bstrLicSource,
        ULONG *pdwRetCode) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetFirstName(
        BSTR *pbstrVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetFirstName(
        BSTR bstrNewVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetLastName(
        BSTR *pbstrVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetLastName(
        BSTR bstrNewVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetOrgName(
        BSTR *pbstrVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetOrgName(
        BSTR bstrNewVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetEmail(
        BSTR *pbstrVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetEmail(
        BSTR bstrNewVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetPhone(
        BSTR *pbstrVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetPhone(
        BSTR bstrNewVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetAddress1(
        BSTR *pbstrVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetAddress1(
        BSTR bstrNewVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetCity(
        BSTR *pbstrVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetCity(
        BSTR bstrNewVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetState(
        BSTR *pbstrVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetState(
        BSTR bstrNewVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetCountryCode(
        BSTR *pbstrVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetCountryCode(
        BSTR bstrNewVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetCountryDesc(
        BSTR *pbstrVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetCountryDesc(
        BSTR bstrNewVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetZip(
        BSTR *pbstrVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetZip(
        BSTR bstrNewVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetIsoLanguage(
        ULONG *pdwVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetIsoLanguage(
        ULONG dwNewVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetMSUpdate(
        BSTR *pbstrVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetMSUpdate(
        BSTR bstrNewVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetMSOffer(
        BSTR *pbstrVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetMSOffer(
        BSTR bstrNewVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetOtherOffer(
        BSTR *pbstrVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetOtherOffer(
        BSTR bstrNewVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetAddress2(
        BSTR *pbstrVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetAddress2(
        BSTR bstrNewVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE AsyncProcessHandshakeRequest(
        LONG bReviseCustInfo) = 0;

    virtual HRESULT STDMETHODCALLTYPE AsyncProcessNewLicenseRequest(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE AsyncProcessReissueLicenseRequest(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE AsyncProcessReviseCustInfoRequest(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetAsyncProcessReturnCode(
        ULONG *pdwRetCode) = 0;

    virtual HRESULT STDMETHODCALLTYPE AsyncProcessDroppedLicenseRequest(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE GenerateInstallationId(
        BSTR *pbstrVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE DepositConfirmationId(
        BSTR bstrVal,
        ULONG *pdwRetCode) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetExpirationInfo(
        ULONG *pdwWPALeft,
        ULONG *pdwEvalLeft) = 0;

    virtual HRESULT STDMETHODCALLTYPE AsyncProcessRegistrationRequest(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE ProcessHandshakeRequest(
        LONG bReviseCustInfo) = 0;

    virtual HRESULT STDMETHODCALLTYPE ProcessNewLicenseRequest(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE ProcessDroppedLicenseRequest(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE ProcessReissueLicenseRequest(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE ProcessReviseCustInfoRequest(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE EnsureInternetConnection(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE SetProductKey(
        LPWSTR pszNewProductKey) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetProductID(
        BSTR *pbstrVal) = 0;

    virtual HRESULT STDMETHODCALLTYPE VerifyCheckDigits(
        BSTR bstrCIDIID,
        LONG *pbValue) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ICOMLicenseAgent, 0xb8cbad79, 0x3f1f, 0x481a, 0xbb,0x0c, 0xe7,0xbb,0xd7,0x7b,0xdd,0xd1)
#endif
#else
typedef struct ICOMLicenseAgentVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ICOMLicenseAgent *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ICOMLicenseAgent *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ICOMLicenseAgent *This);

    /*** IDispatch methods ***/
    HRESULT (STDMETHODCALLTYPE *GetTypeInfoCount)(
        ICOMLicenseAgent *This,
        UINT *pctinfo);

    HRESULT (STDMETHODCALLTYPE *GetTypeInfo)(
        ICOMLicenseAgent *This,
        UINT iTInfo,
        LCID lcid,
        ITypeInfo **ppTInfo);

    HRESULT (STDMETHODCALLTYPE *GetIDsOfNames)(
        ICOMLicenseAgent *This,
        REFIID riid,
        LPOLESTR *rgszNames,
        UINT cNames,
        LCID lcid,
        DISPID *rgDispId);

    HRESULT (STDMETHODCALLTYPE *Invoke)(
        ICOMLicenseAgent *This,
        DISPID dispIdMember,
        REFIID riid,
        LCID lcid,
        WORD wFlags,
        DISPPARAMS *pDispParams,
        VARIANT *pVarResult,
        EXCEPINFO *pExcepInfo,
        UINT *puArgErr);

    /*** ICOMLicenseAgent methods ***/
    HRESULT (STDMETHODCALLTYPE *Initialize)(
        ICOMLicenseAgent *This,
        ULONG dwBPC,
        ULONG dwMode,
        BSTR bstrLicSource,
        ULONG *pdwRetCode);

    HRESULT (STDMETHODCALLTYPE *GetFirstName)(
        ICOMLicenseAgent *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetFirstName)(
        ICOMLicenseAgent *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetLastName)(
        ICOMLicenseAgent *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetLastName)(
        ICOMLicenseAgent *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetOrgName)(
        ICOMLicenseAgent *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetOrgName)(
        ICOMLicenseAgent *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetEmail)(
        ICOMLicenseAgent *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetEmail)(
        ICOMLicenseAgent *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetPhone)(
        ICOMLicenseAgent *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetPhone)(
        ICOMLicenseAgent *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetAddress1)(
        ICOMLicenseAgent *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetAddress1)(
        ICOMLicenseAgent *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetCity)(
        ICOMLicenseAgent *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetCity)(
        ICOMLicenseAgent *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetState)(
        ICOMLicenseAgent *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetState)(
        ICOMLicenseAgent *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetCountryCode)(
        ICOMLicenseAgent *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetCountryCode)(
        ICOMLicenseAgent *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetCountryDesc)(
        ICOMLicenseAgent *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetCountryDesc)(
        ICOMLicenseAgent *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetZip)(
        ICOMLicenseAgent *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetZip)(
        ICOMLicenseAgent *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetIsoLanguage)(
        ICOMLicenseAgent *This,
        ULONG *pdwVal);

    HRESULT (STDMETHODCALLTYPE *SetIsoLanguage)(
        ICOMLicenseAgent *This,
        ULONG dwNewVal);

    HRESULT (STDMETHODCALLTYPE *GetMSUpdate)(
        ICOMLicenseAgent *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetMSUpdate)(
        ICOMLicenseAgent *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetMSOffer)(
        ICOMLicenseAgent *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetMSOffer)(
        ICOMLicenseAgent *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetOtherOffer)(
        ICOMLicenseAgent *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetOtherOffer)(
        ICOMLicenseAgent *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetAddress2)(
        ICOMLicenseAgent *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetAddress2)(
        ICOMLicenseAgent *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *AsyncProcessHandshakeRequest)(
        ICOMLicenseAgent *This,
        LONG bReviseCustInfo);

    HRESULT (STDMETHODCALLTYPE *AsyncProcessNewLicenseRequest)(
        ICOMLicenseAgent *This);

    HRESULT (STDMETHODCALLTYPE *AsyncProcessReissueLicenseRequest)(
        ICOMLicenseAgent *This);

    HRESULT (STDMETHODCALLTYPE *AsyncProcessReviseCustInfoRequest)(
        ICOMLicenseAgent *This);

    HRESULT (STDMETHODCALLTYPE *GetAsyncProcessReturnCode)(
        ICOMLicenseAgent *This,
        ULONG *pdwRetCode);

    HRESULT (STDMETHODCALLTYPE *AsyncProcessDroppedLicenseRequest)(
        ICOMLicenseAgent *This);

    HRESULT (STDMETHODCALLTYPE *GenerateInstallationId)(
        ICOMLicenseAgent *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *DepositConfirmationId)(
        ICOMLicenseAgent *This,
        BSTR bstrVal,
        ULONG *pdwRetCode);

    HRESULT (STDMETHODCALLTYPE *GetExpirationInfo)(
        ICOMLicenseAgent *This,
        ULONG *pdwWPALeft,
        ULONG *pdwEvalLeft);

    HRESULT (STDMETHODCALLTYPE *AsyncProcessRegistrationRequest)(
        ICOMLicenseAgent *This);

    HRESULT (STDMETHODCALLTYPE *ProcessHandshakeRequest)(
        ICOMLicenseAgent *This,
        LONG bReviseCustInfo);

    HRESULT (STDMETHODCALLTYPE *ProcessNewLicenseRequest)(
        ICOMLicenseAgent *This);

    HRESULT (STDMETHODCALLTYPE *ProcessDroppedLicenseRequest)(
        ICOMLicenseAgent *This);

    HRESULT (STDMETHODCALLTYPE *ProcessReissueLicenseRequest)(
        ICOMLicenseAgent *This);

    HRESULT (STDMETHODCALLTYPE *ProcessReviseCustInfoRequest)(
        ICOMLicenseAgent *This);

    HRESULT (STDMETHODCALLTYPE *EnsureInternetConnection)(
        ICOMLicenseAgent *This);

    HRESULT (STDMETHODCALLTYPE *SetProductKey)(
        ICOMLicenseAgent *This,
        LPWSTR pszNewProductKey);

    HRESULT (STDMETHODCALLTYPE *GetProductID)(
        ICOMLicenseAgent *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *VerifyCheckDigits)(
        ICOMLicenseAgent *This,
        BSTR bstrCIDIID,
        LONG *pbValue);

    END_INTERFACE
} ICOMLicenseAgentVtbl;

interface ICOMLicenseAgent {
    CONST_VTBL ICOMLicenseAgentVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ICOMLicenseAgent_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ICOMLicenseAgent_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ICOMLicenseAgent_Release(This) (This)->lpVtbl->Release(This)
/*** IDispatch methods ***/
#define ICOMLicenseAgent_GetTypeInfoCount(This,pctinfo) (This)->lpVtbl->GetTypeInfoCount(This,pctinfo)
#define ICOMLicenseAgent_GetTypeInfo(This,iTInfo,lcid,ppTInfo) (This)->lpVtbl->GetTypeInfo(This,iTInfo,lcid,ppTInfo)
#define ICOMLicenseAgent_GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId) (This)->lpVtbl->GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId)
#define ICOMLicenseAgent_Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr) (This)->lpVtbl->Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr)
/*** ICOMLicenseAgent methods ***/
#define ICOMLicenseAgent_Initialize(This,dwBPC,dwMode,bstrLicSource,pdwRetCode) (This)->lpVtbl->Initialize(This,dwBPC,dwMode,bstrLicSource,pdwRetCode)
#define ICOMLicenseAgent_GetFirstName(This,pbstrVal) (This)->lpVtbl->GetFirstName(This,pbstrVal)
#define ICOMLicenseAgent_SetFirstName(This,bstrNewVal) (This)->lpVtbl->SetFirstName(This,bstrNewVal)
#define ICOMLicenseAgent_GetLastName(This,pbstrVal) (This)->lpVtbl->GetLastName(This,pbstrVal)
#define ICOMLicenseAgent_SetLastName(This,bstrNewVal) (This)->lpVtbl->SetLastName(This,bstrNewVal)
#define ICOMLicenseAgent_GetOrgName(This,pbstrVal) (This)->lpVtbl->GetOrgName(This,pbstrVal)
#define ICOMLicenseAgent_SetOrgName(This,bstrNewVal) (This)->lpVtbl->SetOrgName(This,bstrNewVal)
#define ICOMLicenseAgent_GetEmail(This,pbstrVal) (This)->lpVtbl->GetEmail(This,pbstrVal)
#define ICOMLicenseAgent_SetEmail(This,bstrNewVal) (This)->lpVtbl->SetEmail(This,bstrNewVal)
#define ICOMLicenseAgent_GetPhone(This,pbstrVal) (This)->lpVtbl->GetPhone(This,pbstrVal)
#define ICOMLicenseAgent_SetPhone(This,bstrNewVal) (This)->lpVtbl->SetPhone(This,bstrNewVal)
#define ICOMLicenseAgent_GetAddress1(This,pbstrVal) (This)->lpVtbl->GetAddress1(This,pbstrVal)
#define ICOMLicenseAgent_SetAddress1(This,bstrNewVal) (This)->lpVtbl->SetAddress1(This,bstrNewVal)
#define ICOMLicenseAgent_GetCity(This,pbstrVal) (This)->lpVtbl->GetCity(This,pbstrVal)
#define ICOMLicenseAgent_SetCity(This,bstrNewVal) (This)->lpVtbl->SetCity(This,bstrNewVal)
#define ICOMLicenseAgent_GetState(This,pbstrVal) (This)->lpVtbl->GetState(This,pbstrVal)
#define ICOMLicenseAgent_SetState(This,bstrNewVal) (This)->lpVtbl->SetState(This,bstrNewVal)
#define ICOMLicenseAgent_GetCountryCode(This,pbstrVal) (This)->lpVtbl->GetCountryCode(This,pbstrVal)
#define ICOMLicenseAgent_SetCountryCode(This,bstrNewVal) (This)->lpVtbl->SetCountryCode(This,bstrNewVal)
#define ICOMLicenseAgent_GetCountryDesc(This,pbstrVal) (This)->lpVtbl->GetCountryDesc(This,pbstrVal)
#define ICOMLicenseAgent_SetCountryDesc(This,bstrNewVal) (This)->lpVtbl->SetCountryDesc(This,bstrNewVal)
#define ICOMLicenseAgent_GetZip(This,pbstrVal) (This)->lpVtbl->GetZip(This,pbstrVal)
#define ICOMLicenseAgent_SetZip(This,bstrNewVal) (This)->lpVtbl->SetZip(This,bstrNewVal)
#define ICOMLicenseAgent_GetIsoLanguage(This,pdwVal) (This)->lpVtbl->GetIsoLanguage(This,pdwVal)
#define ICOMLicenseAgent_SetIsoLanguage(This,dwNewVal) (This)->lpVtbl->SetIsoLanguage(This,dwNewVal)
#define ICOMLicenseAgent_GetMSUpdate(This,pbstrVal) (This)->lpVtbl->GetMSUpdate(This,pbstrVal)
#define ICOMLicenseAgent_SetMSUpdate(This,bstrNewVal) (This)->lpVtbl->SetMSUpdate(This,bstrNewVal)
#define ICOMLicenseAgent_GetMSOffer(This,pbstrVal) (This)->lpVtbl->GetMSOffer(This,pbstrVal)
#define ICOMLicenseAgent_SetMSOffer(This,bstrNewVal) (This)->lpVtbl->SetMSOffer(This,bstrNewVal)
#define ICOMLicenseAgent_GetOtherOffer(This,pbstrVal) (This)->lpVtbl->GetOtherOffer(This,pbstrVal)
#define ICOMLicenseAgent_SetOtherOffer(This,bstrNewVal) (This)->lpVtbl->SetOtherOffer(This,bstrNewVal)
#define ICOMLicenseAgent_GetAddress2(This,pbstrVal) (This)->lpVtbl->GetAddress2(This,pbstrVal)
#define ICOMLicenseAgent_SetAddress2(This,bstrNewVal) (This)->lpVtbl->SetAddress2(This,bstrNewVal)
#define ICOMLicenseAgent_AsyncProcessHandshakeRequest(This,bReviseCustInfo) (This)->lpVtbl->AsyncProcessHandshakeRequest(This,bReviseCustInfo)
#define ICOMLicenseAgent_AsyncProcessNewLicenseRequest(This) (This)->lpVtbl->AsyncProcessNewLicenseRequest(This)
#define ICOMLicenseAgent_AsyncProcessReissueLicenseRequest(This) (This)->lpVtbl->AsyncProcessReissueLicenseRequest(This)
#define ICOMLicenseAgent_AsyncProcessReviseCustInfoRequest(This) (This)->lpVtbl->AsyncProcessReviseCustInfoRequest(This)
#define ICOMLicenseAgent_GetAsyncProcessReturnCode(This,pdwRetCode) (This)->lpVtbl->GetAsyncProcessReturnCode(This,pdwRetCode)
#define ICOMLicenseAgent_AsyncProcessDroppedLicenseRequest(This) (This)->lpVtbl->AsyncProcessDroppedLicenseRequest(This)
#define ICOMLicenseAgent_GenerateInstallationId(This,pbstrVal) (This)->lpVtbl->GenerateInstallationId(This,pbstrVal)
#define ICOMLicenseAgent_DepositConfirmationId(This,bstrVal,pdwRetCode) (This)->lpVtbl->DepositConfirmationId(This,bstrVal,pdwRetCode)
#define ICOMLicenseAgent_GetExpirationInfo(This,pdwWPALeft,pdwEvalLeft) (This)->lpVtbl->GetExpirationInfo(This,pdwWPALeft,pdwEvalLeft)
#define ICOMLicenseAgent_AsyncProcessRegistrationRequest(This) (This)->lpVtbl->AsyncProcessRegistrationRequest(This)
#define ICOMLicenseAgent_ProcessHandshakeRequest(This,bReviseCustInfo) (This)->lpVtbl->ProcessHandshakeRequest(This,bReviseCustInfo)
#define ICOMLicenseAgent_ProcessNewLicenseRequest(This) (This)->lpVtbl->ProcessNewLicenseRequest(This)
#define ICOMLicenseAgent_ProcessDroppedLicenseRequest(This) (This)->lpVtbl->ProcessDroppedLicenseRequest(This)
#define ICOMLicenseAgent_ProcessReissueLicenseRequest(This) (This)->lpVtbl->ProcessReissueLicenseRequest(This)
#define ICOMLicenseAgent_ProcessReviseCustInfoRequest(This) (This)->lpVtbl->ProcessReviseCustInfoRequest(This)
#define ICOMLicenseAgent_EnsureInternetConnection(This) (This)->lpVtbl->EnsureInternetConnection(This)
#define ICOMLicenseAgent_SetProductKey(This,pszNewProductKey) (This)->lpVtbl->SetProductKey(This,pszNewProductKey)
#define ICOMLicenseAgent_GetProductID(This,pbstrVal) (This)->lpVtbl->GetProductID(This,pbstrVal)
#define ICOMLicenseAgent_VerifyCheckDigits(This,bstrCIDIID,pbValue) (This)->lpVtbl->VerifyCheckDigits(This,bstrCIDIID,pbValue)
#else
/*** IUnknown methods ***/
static __WIDL_INLINE HRESULT ICOMLicenseAgent_QueryInterface(ICOMLicenseAgent* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static __WIDL_INLINE ULONG ICOMLicenseAgent_AddRef(ICOMLicenseAgent* This) {
    return This->lpVtbl->AddRef(This);
}
static __WIDL_INLINE ULONG ICOMLicenseAgent_Release(ICOMLicenseAgent* This) {
    return This->lpVtbl->Release(This);
}
/*** IDispatch methods ***/
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GetTypeInfoCount(ICOMLicenseAgent* This,UINT *pctinfo) {
    return This->lpVtbl->GetTypeInfoCount(This,pctinfo);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GetTypeInfo(ICOMLicenseAgent* This,UINT iTInfo,LCID lcid,ITypeInfo **ppTInfo) {
    return This->lpVtbl->GetTypeInfo(This,iTInfo,lcid,ppTInfo);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GetIDsOfNames(ICOMLicenseAgent* This,REFIID riid,LPOLESTR *rgszNames,UINT cNames,LCID lcid,DISPID *rgDispId) {
    return This->lpVtbl->GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_Invoke(ICOMLicenseAgent* This,DISPID dispIdMember,REFIID riid,LCID lcid,WORD wFlags,DISPPARAMS *pDispParams,VARIANT *pVarResult,EXCEPINFO *pExcepInfo,UINT *puArgErr) {
    return This->lpVtbl->Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr);
}
/*** ICOMLicenseAgent methods ***/
static __WIDL_INLINE HRESULT ICOMLicenseAgent_Initialize(ICOMLicenseAgent* This,ULONG dwBPC,ULONG dwMode,BSTR bstrLicSource,ULONG *pdwRetCode) {
    return This->lpVtbl->Initialize(This,dwBPC,dwMode,bstrLicSource,pdwRetCode);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GetFirstName(ICOMLicenseAgent* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetFirstName(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_SetFirstName(ICOMLicenseAgent* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetFirstName(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GetLastName(ICOMLicenseAgent* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetLastName(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_SetLastName(ICOMLicenseAgent* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetLastName(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GetOrgName(ICOMLicenseAgent* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetOrgName(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_SetOrgName(ICOMLicenseAgent* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetOrgName(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GetEmail(ICOMLicenseAgent* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetEmail(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_SetEmail(ICOMLicenseAgent* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetEmail(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GetPhone(ICOMLicenseAgent* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetPhone(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_SetPhone(ICOMLicenseAgent* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetPhone(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GetAddress1(ICOMLicenseAgent* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetAddress1(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_SetAddress1(ICOMLicenseAgent* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetAddress1(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GetCity(ICOMLicenseAgent* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetCity(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_SetCity(ICOMLicenseAgent* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetCity(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GetState(ICOMLicenseAgent* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetState(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_SetState(ICOMLicenseAgent* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetState(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GetCountryCode(ICOMLicenseAgent* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetCountryCode(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_SetCountryCode(ICOMLicenseAgent* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetCountryCode(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GetCountryDesc(ICOMLicenseAgent* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetCountryDesc(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_SetCountryDesc(ICOMLicenseAgent* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetCountryDesc(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GetZip(ICOMLicenseAgent* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetZip(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_SetZip(ICOMLicenseAgent* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetZip(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GetIsoLanguage(ICOMLicenseAgent* This,ULONG *pdwVal) {
    return This->lpVtbl->GetIsoLanguage(This,pdwVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_SetIsoLanguage(ICOMLicenseAgent* This,ULONG dwNewVal) {
    return This->lpVtbl->SetIsoLanguage(This,dwNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GetMSUpdate(ICOMLicenseAgent* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetMSUpdate(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_SetMSUpdate(ICOMLicenseAgent* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetMSUpdate(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GetMSOffer(ICOMLicenseAgent* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetMSOffer(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_SetMSOffer(ICOMLicenseAgent* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetMSOffer(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GetOtherOffer(ICOMLicenseAgent* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetOtherOffer(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_SetOtherOffer(ICOMLicenseAgent* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetOtherOffer(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GetAddress2(ICOMLicenseAgent* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetAddress2(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_SetAddress2(ICOMLicenseAgent* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetAddress2(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_AsyncProcessHandshakeRequest(ICOMLicenseAgent* This,LONG bReviseCustInfo) {
    return This->lpVtbl->AsyncProcessHandshakeRequest(This,bReviseCustInfo);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_AsyncProcessNewLicenseRequest(ICOMLicenseAgent* This) {
    return This->lpVtbl->AsyncProcessNewLicenseRequest(This);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_AsyncProcessReissueLicenseRequest(ICOMLicenseAgent* This) {
    return This->lpVtbl->AsyncProcessReissueLicenseRequest(This);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_AsyncProcessReviseCustInfoRequest(ICOMLicenseAgent* This) {
    return This->lpVtbl->AsyncProcessReviseCustInfoRequest(This);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GetAsyncProcessReturnCode(ICOMLicenseAgent* This,ULONG *pdwRetCode) {
    return This->lpVtbl->GetAsyncProcessReturnCode(This,pdwRetCode);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_AsyncProcessDroppedLicenseRequest(ICOMLicenseAgent* This) {
    return This->lpVtbl->AsyncProcessDroppedLicenseRequest(This);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GenerateInstallationId(ICOMLicenseAgent* This,BSTR *pbstrVal) {
    return This->lpVtbl->GenerateInstallationId(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_DepositConfirmationId(ICOMLicenseAgent* This,BSTR bstrVal,ULONG *pdwRetCode) {
    return This->lpVtbl->DepositConfirmationId(This,bstrVal,pdwRetCode);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GetExpirationInfo(ICOMLicenseAgent* This,ULONG *pdwWPALeft,ULONG *pdwEvalLeft) {
    return This->lpVtbl->GetExpirationInfo(This,pdwWPALeft,pdwEvalLeft);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_AsyncProcessRegistrationRequest(ICOMLicenseAgent* This) {
    return This->lpVtbl->AsyncProcessRegistrationRequest(This);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_ProcessHandshakeRequest(ICOMLicenseAgent* This,LONG bReviseCustInfo) {
    return This->lpVtbl->ProcessHandshakeRequest(This,bReviseCustInfo);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_ProcessNewLicenseRequest(ICOMLicenseAgent* This) {
    return This->lpVtbl->ProcessNewLicenseRequest(This);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_ProcessDroppedLicenseRequest(ICOMLicenseAgent* This) {
    return This->lpVtbl->ProcessDroppedLicenseRequest(This);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_ProcessReissueLicenseRequest(ICOMLicenseAgent* This) {
    return This->lpVtbl->ProcessReissueLicenseRequest(This);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_ProcessReviseCustInfoRequest(ICOMLicenseAgent* This) {
    return This->lpVtbl->ProcessReviseCustInfoRequest(This);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_EnsureInternetConnection(ICOMLicenseAgent* This) {
    return This->lpVtbl->EnsureInternetConnection(This);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_SetProductKey(ICOMLicenseAgent* This,LPWSTR pszNewProductKey) {
    return This->lpVtbl->SetProductKey(This,pszNewProductKey);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_GetProductID(ICOMLicenseAgent* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetProductID(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent_VerifyCheckDigits(ICOMLicenseAgent* This,BSTR bstrCIDIID,LONG *pbValue) {
    return This->lpVtbl->VerifyCheckDigits(This,bstrCIDIID,pbValue);
}
#endif
#endif

#endif


#endif  /* __ICOMLicenseAgent_INTERFACE_DEFINED__ */

/*****************************************************************************
 * ICOMLicenseAgent2 interface
 */
#ifndef __ICOMLicenseAgent2_INTERFACE_DEFINED__
#define __ICOMLicenseAgent2_INTERFACE_DEFINED__

DEFINE_GUID(IID_ICOMLicenseAgent2, 0x6a07c5a3, 0x9c67, 0x4bb6, 0xb0,0x20, 0xec,0xbe,0x7f,0xdf,0xd3,0x26);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("6a07c5a3-9c67-4bb6-b020-ecbe7fdfd326")
ICOMLicenseAgent2 : public ICOMLicenseAgent
{
    virtual HRESULT STDMETHODCALLTYPE SetReminders(
        LONG bValue) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetReminders(
        LONG *pbValue) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetKeyType(
        ULONG *pdwKeyType) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ICOMLicenseAgent2, 0x6a07c5a3, 0x9c67, 0x4bb6, 0xb0,0x20, 0xec,0xbe,0x7f,0xdf,0xd3,0x26)
#endif
#else
typedef struct ICOMLicenseAgent2Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ICOMLicenseAgent2 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ICOMLicenseAgent2 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ICOMLicenseAgent2 *This);

    /*** IDispatch methods ***/
    HRESULT (STDMETHODCALLTYPE *GetTypeInfoCount)(
        ICOMLicenseAgent2 *This,
        UINT *pctinfo);

    HRESULT (STDMETHODCALLTYPE *GetTypeInfo)(
        ICOMLicenseAgent2 *This,
        UINT iTInfo,
        LCID lcid,
        ITypeInfo **ppTInfo);

    HRESULT (STDMETHODCALLTYPE *GetIDsOfNames)(
        ICOMLicenseAgent2 *This,
        REFIID riid,
        LPOLESTR *rgszNames,
        UINT cNames,
        LCID lcid,
        DISPID *rgDispId);

    HRESULT (STDMETHODCALLTYPE *Invoke)(
        ICOMLicenseAgent2 *This,
        DISPID dispIdMember,
        REFIID riid,
        LCID lcid,
        WORD wFlags,
        DISPPARAMS *pDispParams,
        VARIANT *pVarResult,
        EXCEPINFO *pExcepInfo,
        UINT *puArgErr);

    /*** ICOMLicenseAgent methods ***/
    HRESULT (STDMETHODCALLTYPE *Initialize)(
        ICOMLicenseAgent2 *This,
        ULONG dwBPC,
        ULONG dwMode,
        BSTR bstrLicSource,
        ULONG *pdwRetCode);

    HRESULT (STDMETHODCALLTYPE *GetFirstName)(
        ICOMLicenseAgent2 *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetFirstName)(
        ICOMLicenseAgent2 *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetLastName)(
        ICOMLicenseAgent2 *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetLastName)(
        ICOMLicenseAgent2 *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetOrgName)(
        ICOMLicenseAgent2 *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetOrgName)(
        ICOMLicenseAgent2 *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetEmail)(
        ICOMLicenseAgent2 *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetEmail)(
        ICOMLicenseAgent2 *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetPhone)(
        ICOMLicenseAgent2 *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetPhone)(
        ICOMLicenseAgent2 *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetAddress1)(
        ICOMLicenseAgent2 *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetAddress1)(
        ICOMLicenseAgent2 *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetCity)(
        ICOMLicenseAgent2 *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetCity)(
        ICOMLicenseAgent2 *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetState)(
        ICOMLicenseAgent2 *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetState)(
        ICOMLicenseAgent2 *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetCountryCode)(
        ICOMLicenseAgent2 *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetCountryCode)(
        ICOMLicenseAgent2 *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetCountryDesc)(
        ICOMLicenseAgent2 *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetCountryDesc)(
        ICOMLicenseAgent2 *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetZip)(
        ICOMLicenseAgent2 *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetZip)(
        ICOMLicenseAgent2 *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetIsoLanguage)(
        ICOMLicenseAgent2 *This,
        ULONG *pdwVal);

    HRESULT (STDMETHODCALLTYPE *SetIsoLanguage)(
        ICOMLicenseAgent2 *This,
        ULONG dwNewVal);

    HRESULT (STDMETHODCALLTYPE *GetMSUpdate)(
        ICOMLicenseAgent2 *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetMSUpdate)(
        ICOMLicenseAgent2 *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetMSOffer)(
        ICOMLicenseAgent2 *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetMSOffer)(
        ICOMLicenseAgent2 *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetOtherOffer)(
        ICOMLicenseAgent2 *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetOtherOffer)(
        ICOMLicenseAgent2 *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *GetAddress2)(
        ICOMLicenseAgent2 *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *SetAddress2)(
        ICOMLicenseAgent2 *This,
        BSTR bstrNewVal);

    HRESULT (STDMETHODCALLTYPE *AsyncProcessHandshakeRequest)(
        ICOMLicenseAgent2 *This,
        LONG bReviseCustInfo);

    HRESULT (STDMETHODCALLTYPE *AsyncProcessNewLicenseRequest)(
        ICOMLicenseAgent2 *This);

    HRESULT (STDMETHODCALLTYPE *AsyncProcessReissueLicenseRequest)(
        ICOMLicenseAgent2 *This);

    HRESULT (STDMETHODCALLTYPE *AsyncProcessReviseCustInfoRequest)(
        ICOMLicenseAgent2 *This);

    HRESULT (STDMETHODCALLTYPE *GetAsyncProcessReturnCode)(
        ICOMLicenseAgent2 *This,
        ULONG *pdwRetCode);

    HRESULT (STDMETHODCALLTYPE *AsyncProcessDroppedLicenseRequest)(
        ICOMLicenseAgent2 *This);

    HRESULT (STDMETHODCALLTYPE *GenerateInstallationId)(
        ICOMLicenseAgent2 *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *DepositConfirmationId)(
        ICOMLicenseAgent2 *This,
        BSTR bstrVal,
        ULONG *pdwRetCode);

    HRESULT (STDMETHODCALLTYPE *GetExpirationInfo)(
        ICOMLicenseAgent2 *This,
        ULONG *pdwWPALeft,
        ULONG *pdwEvalLeft);

    HRESULT (STDMETHODCALLTYPE *AsyncProcessRegistrationRequest)(
        ICOMLicenseAgent2 *This);

    HRESULT (STDMETHODCALLTYPE *ProcessHandshakeRequest)(
        ICOMLicenseAgent2 *This,
        LONG bReviseCustInfo);

    HRESULT (STDMETHODCALLTYPE *ProcessNewLicenseRequest)(
        ICOMLicenseAgent2 *This);

    HRESULT (STDMETHODCALLTYPE *ProcessDroppedLicenseRequest)(
        ICOMLicenseAgent2 *This);

    HRESULT (STDMETHODCALLTYPE *ProcessReissueLicenseRequest)(
        ICOMLicenseAgent2 *This);

    HRESULT (STDMETHODCALLTYPE *ProcessReviseCustInfoRequest)(
        ICOMLicenseAgent2 *This);

    HRESULT (STDMETHODCALLTYPE *EnsureInternetConnection)(
        ICOMLicenseAgent2 *This);

    HRESULT (STDMETHODCALLTYPE *SetProductKey)(
        ICOMLicenseAgent2 *This,
        LPWSTR pszNewProductKey);

    HRESULT (STDMETHODCALLTYPE *GetProductID)(
        ICOMLicenseAgent2 *This,
        BSTR *pbstrVal);

    HRESULT (STDMETHODCALLTYPE *VerifyCheckDigits)(
        ICOMLicenseAgent2 *This,
        BSTR bstrCIDIID,
        LONG *pbValue);

    /*** ICOMLicenseAgent2 methods ***/
    HRESULT (STDMETHODCALLTYPE *SetReminders)(
        ICOMLicenseAgent2 *This,
        LONG bValue);

    HRESULT (STDMETHODCALLTYPE *GetReminders)(
        ICOMLicenseAgent2 *This,
        LONG *pbValue);

    HRESULT (STDMETHODCALLTYPE *GetKeyType)(
        ICOMLicenseAgent2 *This,
        ULONG *pdwKeyType);

    END_INTERFACE
} ICOMLicenseAgent2Vtbl;

interface ICOMLicenseAgent2 {
    CONST_VTBL ICOMLicenseAgent2Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ICOMLicenseAgent2_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ICOMLicenseAgent2_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ICOMLicenseAgent2_Release(This) (This)->lpVtbl->Release(This)
/*** IDispatch methods ***/
#define ICOMLicenseAgent2_GetTypeInfoCount(This,pctinfo) (This)->lpVtbl->GetTypeInfoCount(This,pctinfo)
#define ICOMLicenseAgent2_GetTypeInfo(This,iTInfo,lcid,ppTInfo) (This)->lpVtbl->GetTypeInfo(This,iTInfo,lcid,ppTInfo)
#define ICOMLicenseAgent2_GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId) (This)->lpVtbl->GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId)
#define ICOMLicenseAgent2_Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr) (This)->lpVtbl->Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr)
/*** ICOMLicenseAgent methods ***/
#define ICOMLicenseAgent2_Initialize(This,dwBPC,dwMode,bstrLicSource,pdwRetCode) (This)->lpVtbl->Initialize(This,dwBPC,dwMode,bstrLicSource,pdwRetCode)
#define ICOMLicenseAgent2_GetFirstName(This,pbstrVal) (This)->lpVtbl->GetFirstName(This,pbstrVal)
#define ICOMLicenseAgent2_SetFirstName(This,bstrNewVal) (This)->lpVtbl->SetFirstName(This,bstrNewVal)
#define ICOMLicenseAgent2_GetLastName(This,pbstrVal) (This)->lpVtbl->GetLastName(This,pbstrVal)
#define ICOMLicenseAgent2_SetLastName(This,bstrNewVal) (This)->lpVtbl->SetLastName(This,bstrNewVal)
#define ICOMLicenseAgent2_GetOrgName(This,pbstrVal) (This)->lpVtbl->GetOrgName(This,pbstrVal)
#define ICOMLicenseAgent2_SetOrgName(This,bstrNewVal) (This)->lpVtbl->SetOrgName(This,bstrNewVal)
#define ICOMLicenseAgent2_GetEmail(This,pbstrVal) (This)->lpVtbl->GetEmail(This,pbstrVal)
#define ICOMLicenseAgent2_SetEmail(This,bstrNewVal) (This)->lpVtbl->SetEmail(This,bstrNewVal)
#define ICOMLicenseAgent2_GetPhone(This,pbstrVal) (This)->lpVtbl->GetPhone(This,pbstrVal)
#define ICOMLicenseAgent2_SetPhone(This,bstrNewVal) (This)->lpVtbl->SetPhone(This,bstrNewVal)
#define ICOMLicenseAgent2_GetAddress1(This,pbstrVal) (This)->lpVtbl->GetAddress1(This,pbstrVal)
#define ICOMLicenseAgent2_SetAddress1(This,bstrNewVal) (This)->lpVtbl->SetAddress1(This,bstrNewVal)
#define ICOMLicenseAgent2_GetCity(This,pbstrVal) (This)->lpVtbl->GetCity(This,pbstrVal)
#define ICOMLicenseAgent2_SetCity(This,bstrNewVal) (This)->lpVtbl->SetCity(This,bstrNewVal)
#define ICOMLicenseAgent2_GetState(This,pbstrVal) (This)->lpVtbl->GetState(This,pbstrVal)
#define ICOMLicenseAgent2_SetState(This,bstrNewVal) (This)->lpVtbl->SetState(This,bstrNewVal)
#define ICOMLicenseAgent2_GetCountryCode(This,pbstrVal) (This)->lpVtbl->GetCountryCode(This,pbstrVal)
#define ICOMLicenseAgent2_SetCountryCode(This,bstrNewVal) (This)->lpVtbl->SetCountryCode(This,bstrNewVal)
#define ICOMLicenseAgent2_GetCountryDesc(This,pbstrVal) (This)->lpVtbl->GetCountryDesc(This,pbstrVal)
#define ICOMLicenseAgent2_SetCountryDesc(This,bstrNewVal) (This)->lpVtbl->SetCountryDesc(This,bstrNewVal)
#define ICOMLicenseAgent2_GetZip(This,pbstrVal) (This)->lpVtbl->GetZip(This,pbstrVal)
#define ICOMLicenseAgent2_SetZip(This,bstrNewVal) (This)->lpVtbl->SetZip(This,bstrNewVal)
#define ICOMLicenseAgent2_GetIsoLanguage(This,pdwVal) (This)->lpVtbl->GetIsoLanguage(This,pdwVal)
#define ICOMLicenseAgent2_SetIsoLanguage(This,dwNewVal) (This)->lpVtbl->SetIsoLanguage(This,dwNewVal)
#define ICOMLicenseAgent2_GetMSUpdate(This,pbstrVal) (This)->lpVtbl->GetMSUpdate(This,pbstrVal)
#define ICOMLicenseAgent2_SetMSUpdate(This,bstrNewVal) (This)->lpVtbl->SetMSUpdate(This,bstrNewVal)
#define ICOMLicenseAgent2_GetMSOffer(This,pbstrVal) (This)->lpVtbl->GetMSOffer(This,pbstrVal)
#define ICOMLicenseAgent2_SetMSOffer(This,bstrNewVal) (This)->lpVtbl->SetMSOffer(This,bstrNewVal)
#define ICOMLicenseAgent2_GetOtherOffer(This,pbstrVal) (This)->lpVtbl->GetOtherOffer(This,pbstrVal)
#define ICOMLicenseAgent2_SetOtherOffer(This,bstrNewVal) (This)->lpVtbl->SetOtherOffer(This,bstrNewVal)
#define ICOMLicenseAgent2_GetAddress2(This,pbstrVal) (This)->lpVtbl->GetAddress2(This,pbstrVal)
#define ICOMLicenseAgent2_SetAddress2(This,bstrNewVal) (This)->lpVtbl->SetAddress2(This,bstrNewVal)
#define ICOMLicenseAgent2_AsyncProcessHandshakeRequest(This,bReviseCustInfo) (This)->lpVtbl->AsyncProcessHandshakeRequest(This,bReviseCustInfo)
#define ICOMLicenseAgent2_AsyncProcessNewLicenseRequest(This) (This)->lpVtbl->AsyncProcessNewLicenseRequest(This)
#define ICOMLicenseAgent2_AsyncProcessReissueLicenseRequest(This) (This)->lpVtbl->AsyncProcessReissueLicenseRequest(This)
#define ICOMLicenseAgent2_AsyncProcessReviseCustInfoRequest(This) (This)->lpVtbl->AsyncProcessReviseCustInfoRequest(This)
#define ICOMLicenseAgent2_GetAsyncProcessReturnCode(This,pdwRetCode) (This)->lpVtbl->GetAsyncProcessReturnCode(This,pdwRetCode)
#define ICOMLicenseAgent2_AsyncProcessDroppedLicenseRequest(This) (This)->lpVtbl->AsyncProcessDroppedLicenseRequest(This)
#define ICOMLicenseAgent2_GenerateInstallationId(This,pbstrVal) (This)->lpVtbl->GenerateInstallationId(This,pbstrVal)
#define ICOMLicenseAgent2_DepositConfirmationId(This,bstrVal,pdwRetCode) (This)->lpVtbl->DepositConfirmationId(This,bstrVal,pdwRetCode)
#define ICOMLicenseAgent2_GetExpirationInfo(This,pdwWPALeft,pdwEvalLeft) (This)->lpVtbl->GetExpirationInfo(This,pdwWPALeft,pdwEvalLeft)
#define ICOMLicenseAgent2_AsyncProcessRegistrationRequest(This) (This)->lpVtbl->AsyncProcessRegistrationRequest(This)
#define ICOMLicenseAgent2_ProcessHandshakeRequest(This,bReviseCustInfo) (This)->lpVtbl->ProcessHandshakeRequest(This,bReviseCustInfo)
#define ICOMLicenseAgent2_ProcessNewLicenseRequest(This) (This)->lpVtbl->ProcessNewLicenseRequest(This)
#define ICOMLicenseAgent2_ProcessDroppedLicenseRequest(This) (This)->lpVtbl->ProcessDroppedLicenseRequest(This)
#define ICOMLicenseAgent2_ProcessReissueLicenseRequest(This) (This)->lpVtbl->ProcessReissueLicenseRequest(This)
#define ICOMLicenseAgent2_ProcessReviseCustInfoRequest(This) (This)->lpVtbl->ProcessReviseCustInfoRequest(This)
#define ICOMLicenseAgent2_EnsureInternetConnection(This) (This)->lpVtbl->EnsureInternetConnection(This)
#define ICOMLicenseAgent2_SetProductKey(This,pszNewProductKey) (This)->lpVtbl->SetProductKey(This,pszNewProductKey)
#define ICOMLicenseAgent2_GetProductID(This,pbstrVal) (This)->lpVtbl->GetProductID(This,pbstrVal)
#define ICOMLicenseAgent2_VerifyCheckDigits(This,bstrCIDIID,pbValue) (This)->lpVtbl->VerifyCheckDigits(This,bstrCIDIID,pbValue)
/*** ICOMLicenseAgent2 methods ***/
#define ICOMLicenseAgent2_SetReminders(This,bValue) (This)->lpVtbl->SetReminders(This,bValue)
#define ICOMLicenseAgent2_GetReminders(This,pbValue) (This)->lpVtbl->GetReminders(This,pbValue)
#define ICOMLicenseAgent2_GetKeyType(This,pdwKeyType) (This)->lpVtbl->GetKeyType(This,pdwKeyType)
#else
/*** IUnknown methods ***/
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_QueryInterface(ICOMLicenseAgent2* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static __WIDL_INLINE ULONG ICOMLicenseAgent2_AddRef(ICOMLicenseAgent2* This) {
    return This->lpVtbl->AddRef(This);
}
static __WIDL_INLINE ULONG ICOMLicenseAgent2_Release(ICOMLicenseAgent2* This) {
    return This->lpVtbl->Release(This);
}
/*** IDispatch methods ***/
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetTypeInfoCount(ICOMLicenseAgent2* This,UINT *pctinfo) {
    return This->lpVtbl->GetTypeInfoCount(This,pctinfo);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetTypeInfo(ICOMLicenseAgent2* This,UINT iTInfo,LCID lcid,ITypeInfo **ppTInfo) {
    return This->lpVtbl->GetTypeInfo(This,iTInfo,lcid,ppTInfo);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetIDsOfNames(ICOMLicenseAgent2* This,REFIID riid,LPOLESTR *rgszNames,UINT cNames,LCID lcid,DISPID *rgDispId) {
    return This->lpVtbl->GetIDsOfNames(This,riid,rgszNames,cNames,lcid,rgDispId);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_Invoke(ICOMLicenseAgent2* This,DISPID dispIdMember,REFIID riid,LCID lcid,WORD wFlags,DISPPARAMS *pDispParams,VARIANT *pVarResult,EXCEPINFO *pExcepInfo,UINT *puArgErr) {
    return This->lpVtbl->Invoke(This,dispIdMember,riid,lcid,wFlags,pDispParams,pVarResult,pExcepInfo,puArgErr);
}
/*** ICOMLicenseAgent methods ***/
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_Initialize(ICOMLicenseAgent2* This,ULONG dwBPC,ULONG dwMode,BSTR bstrLicSource,ULONG *pdwRetCode) {
    return This->lpVtbl->Initialize(This,dwBPC,dwMode,bstrLicSource,pdwRetCode);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetFirstName(ICOMLicenseAgent2* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetFirstName(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_SetFirstName(ICOMLicenseAgent2* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetFirstName(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetLastName(ICOMLicenseAgent2* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetLastName(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_SetLastName(ICOMLicenseAgent2* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetLastName(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetOrgName(ICOMLicenseAgent2* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetOrgName(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_SetOrgName(ICOMLicenseAgent2* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetOrgName(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetEmail(ICOMLicenseAgent2* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetEmail(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_SetEmail(ICOMLicenseAgent2* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetEmail(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetPhone(ICOMLicenseAgent2* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetPhone(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_SetPhone(ICOMLicenseAgent2* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetPhone(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetAddress1(ICOMLicenseAgent2* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetAddress1(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_SetAddress1(ICOMLicenseAgent2* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetAddress1(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetCity(ICOMLicenseAgent2* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetCity(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_SetCity(ICOMLicenseAgent2* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetCity(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetState(ICOMLicenseAgent2* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetState(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_SetState(ICOMLicenseAgent2* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetState(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetCountryCode(ICOMLicenseAgent2* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetCountryCode(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_SetCountryCode(ICOMLicenseAgent2* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetCountryCode(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetCountryDesc(ICOMLicenseAgent2* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetCountryDesc(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_SetCountryDesc(ICOMLicenseAgent2* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetCountryDesc(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetZip(ICOMLicenseAgent2* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetZip(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_SetZip(ICOMLicenseAgent2* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetZip(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetIsoLanguage(ICOMLicenseAgent2* This,ULONG *pdwVal) {
    return This->lpVtbl->GetIsoLanguage(This,pdwVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_SetIsoLanguage(ICOMLicenseAgent2* This,ULONG dwNewVal) {
    return This->lpVtbl->SetIsoLanguage(This,dwNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetMSUpdate(ICOMLicenseAgent2* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetMSUpdate(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_SetMSUpdate(ICOMLicenseAgent2* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetMSUpdate(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetMSOffer(ICOMLicenseAgent2* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetMSOffer(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_SetMSOffer(ICOMLicenseAgent2* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetMSOffer(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetOtherOffer(ICOMLicenseAgent2* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetOtherOffer(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_SetOtherOffer(ICOMLicenseAgent2* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetOtherOffer(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetAddress2(ICOMLicenseAgent2* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetAddress2(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_SetAddress2(ICOMLicenseAgent2* This,BSTR bstrNewVal) {
    return This->lpVtbl->SetAddress2(This,bstrNewVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_AsyncProcessHandshakeRequest(ICOMLicenseAgent2* This,LONG bReviseCustInfo) {
    return This->lpVtbl->AsyncProcessHandshakeRequest(This,bReviseCustInfo);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_AsyncProcessNewLicenseRequest(ICOMLicenseAgent2* This) {
    return This->lpVtbl->AsyncProcessNewLicenseRequest(This);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_AsyncProcessReissueLicenseRequest(ICOMLicenseAgent2* This) {
    return This->lpVtbl->AsyncProcessReissueLicenseRequest(This);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_AsyncProcessReviseCustInfoRequest(ICOMLicenseAgent2* This) {
    return This->lpVtbl->AsyncProcessReviseCustInfoRequest(This);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetAsyncProcessReturnCode(ICOMLicenseAgent2* This,ULONG *pdwRetCode) {
    return This->lpVtbl->GetAsyncProcessReturnCode(This,pdwRetCode);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_AsyncProcessDroppedLicenseRequest(ICOMLicenseAgent2* This) {
    return This->lpVtbl->AsyncProcessDroppedLicenseRequest(This);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GenerateInstallationId(ICOMLicenseAgent2* This,BSTR *pbstrVal) {
    return This->lpVtbl->GenerateInstallationId(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_DepositConfirmationId(ICOMLicenseAgent2* This,BSTR bstrVal,ULONG *pdwRetCode) {
    return This->lpVtbl->DepositConfirmationId(This,bstrVal,pdwRetCode);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetExpirationInfo(ICOMLicenseAgent2* This,ULONG *pdwWPALeft,ULONG *pdwEvalLeft) {
    return This->lpVtbl->GetExpirationInfo(This,pdwWPALeft,pdwEvalLeft);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_AsyncProcessRegistrationRequest(ICOMLicenseAgent2* This) {
    return This->lpVtbl->AsyncProcessRegistrationRequest(This);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_ProcessHandshakeRequest(ICOMLicenseAgent2* This,LONG bReviseCustInfo) {
    return This->lpVtbl->ProcessHandshakeRequest(This,bReviseCustInfo);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_ProcessNewLicenseRequest(ICOMLicenseAgent2* This) {
    return This->lpVtbl->ProcessNewLicenseRequest(This);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_ProcessDroppedLicenseRequest(ICOMLicenseAgent2* This) {
    return This->lpVtbl->ProcessDroppedLicenseRequest(This);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_ProcessReissueLicenseRequest(ICOMLicenseAgent2* This) {
    return This->lpVtbl->ProcessReissueLicenseRequest(This);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_ProcessReviseCustInfoRequest(ICOMLicenseAgent2* This) {
    return This->lpVtbl->ProcessReviseCustInfoRequest(This);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_EnsureInternetConnection(ICOMLicenseAgent2* This) {
    return This->lpVtbl->EnsureInternetConnection(This);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_SetProductKey(ICOMLicenseAgent2* This,LPWSTR pszNewProductKey) {
    return This->lpVtbl->SetProductKey(This,pszNewProductKey);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetProductID(ICOMLicenseAgent2* This,BSTR *pbstrVal) {
    return This->lpVtbl->GetProductID(This,pbstrVal);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_VerifyCheckDigits(ICOMLicenseAgent2* This,BSTR bstrCIDIID,LONG *pbValue) {
    return This->lpVtbl->VerifyCheckDigits(This,bstrCIDIID,pbValue);
}
/*** ICOMLicenseAgent2 methods ***/
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_SetReminders(ICOMLicenseAgent2* This,LONG bValue) {
    return This->lpVtbl->SetReminders(This,bValue);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetReminders(ICOMLicenseAgent2* This,LONG *pbValue) {
    return This->lpVtbl->GetReminders(This,pbValue);
}
static __WIDL_INLINE HRESULT ICOMLicenseAgent2_GetKeyType(ICOMLicenseAgent2* This,ULONG *pdwKeyType) {
    return This->lpVtbl->GetKeyType(This,pdwKeyType);
}
#endif
#endif

#endif


#endif  /* __ICOMLicenseAgent2_INTERFACE_DEFINED__ */

#endif /* __LICDLLLib_LIBRARY_DEFINED__ */
/* Begin additional prototypes for all interfaces */

ULONG           __RPC_USER BSTR_UserSize     (ULONG *, ULONG, BSTR *);
unsigned char * __RPC_USER BSTR_UserMarshal  (ULONG *, unsigned char *, BSTR *);
unsigned char * __RPC_USER BSTR_UserUnmarshal(ULONG *, unsigned char *, BSTR *);
void            __RPC_USER BSTR_UserFree     (ULONG *, BSTR *);

/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __licdll_h__ */
